name: cp
description: "A secure, fully offline steganography app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  image: ^4.1.4
  path_provider: ^2.1.1
  path: ^1.8.3
  encrypt: ^5.0.3
  pointycastle: ^3.7.3
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
